version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graddlerwars
      MYSQL_USER: graddlerwars
      MYSQL_PASSWORD: graddlerwars
    volumes:
      - ./questions:/docker-entrypoint-initdb.d
    restart: always
  app:
    depends_on:
      - mysql
    build: .
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "traefik.frontend.rule=Host:graddlerwars.de"
      - "traefik.port=3000"
