version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graddlerwars
      MYSQL_USER: graddlerwars
      MYSQL_PASSWORD: graddlerwars
    volumes:
      - ./questions:/docker-entrypoint-initdb.d
    networks:
      - internal
    restart: always
  app:
    depends_on:
      - mysql
    build: .
    ports:
      - $EXTERNAL_PORT:3000
    networks: 
      - proxy
      - internal
    restart: always
    labels:
      - "traefik.frontend.rule=Host:$TRAEFIK_HOST"
      - "traefik.port=3000"
      - "traefik.docker.network=proxy"
    environment:
      - TRAEFIK_HOST=localhost
      - EXTERNAL_PORT=3000
networks:
  proxy:
    external: true
  internal:
    external: false
